### ISSUE TITLE
json.inc

### ISSUE THREAD

**Issue by ASMHSE** [ObjAsm/ObjAsm-C.2#1]
close to line 858 must be:

mov dSize, eax
or
 invoke WideCharToMultiByte, CP_ACP, 0, pBegin, dLen, pValue, dLen, NULL, NULL

**Comment by ObjAsm** [comment]
Hi ASMHSE
Almost at the same time you opened the issue and I posted new code, which I have revised exactly at this point. Could you please check if the change applies to the new code?
Thank you.

**Comment by ASMHSE** [comment]
I posted some seconds after new code.
I readed a few lines, and just noted the dSize look undefined in line 859. Perhaps to erase "mov dSize, eax" was accidental.

**Comment by ObjAsm** [comment]
OK, got it. 
Instead of dSize it should be dLen. I will remove dSize completely, as it no longer makes sense.
Thanks.
